language: perl
perl: [ "5.20", 5.18 ]
pre_install:
   - cpanm --quiet --notest --skip-satisfied Dist::Zilla
   - cpanm --quiet --notest --skip-satisfied Spreadsheet::ParseExcel
   - cpanm --quiet --notest --skip-satisfied Spreadsheet::WriteExcel
   - dzil authordeps | grep -vP '[^\w:]' | xargs -n 5 -P 10 cpanm --quiet --notest --skip-satisfied
   - export RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1 HARNESS_OPTIONS=j10:c HARNESS_TIMER=1
   - dzil listdeps | grep -vP '[^\w:]' | cpanm
install:
   - dzil smoke --release --author
