language: perl
perl: [ "5.20", 5.18 ]
install:
    - |
       cat << M | cpanm --quiet --notest --skip-satisfied
           Dist::Zilla
           Spreadsheet::ParseExcel
       M
       dzil authordeps |
            grep -vP '[^\w:]' |
            xargs -n 5 -P 10 cpanm --quiet --notest --skip-satisfied
        export RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1 HARNESS_OPTIONS=j10:c HARNESS_TIMER=1
         dzil listdeps | grep -vP '[^\w:]' | cpanm --verbose
script:
    - |
        dzil smoke --release --author
